// Local fallback data - Only used if remote fetch and cache both fail
// This file serves as emergency backup when network is unavailable

const Map<String, dynamic> appConstantDataJson = {
  "mainCategories": {
    "women": "Women_Apparel,UniSexA,Sports_&_Outdoor",
    "men": "Men_Apparel,UniSexA,Sports_&_Outdoor",
    "kids": "Baby_&_Kids,UniSexK",
    "bags": "Bags_&_Luggage",
    "shoes": "Shoes,Baby_&_Kids",
    "underwear": "Underwear_&_Sleepwear",
    "home": "Home_&_Living",
    "accessories": "Apparel_&_Accessories",
    "office": "Office_&_School_Supplies",
    "beauty": "Beauty_&_Health",
    "sports": "Sports_&_Outdoor",
    "electronics": "Electronics",
  },
  "subCategories": {
    "women":
        "WashaqWomen,WashaqUni,Arabian_Wear,Women_Beachwear,Women_Bottoms,Women_Clothing,Women_Co_Ords,Women_Denim,Women_Dresses,Women_Jumpsuits_Bodysuits,Women_Knitwear,Women_Outerwear,Women_Party_Wear,Women_Suits,Women_Sweatshirts,Women_Tops,Women_Activewear,Women_Sleepwear,Women_Sexy_Lingerie,Women_Bras_&_Panties,Women_Briefs",
    "womenPlus":
        "WashaqPlusWomen,Plus_Size_Dresses,Plus_Size_Bottoms,Plus_Size_Outerwears,Plus_Size_Denim,Plus_Size_Tops,Plus_Size_Co_Ords,Plus_Size_Suits,Plus_Size_Jumpsuits_Bodysuits,Plus_Size_Arabian_Wear,Plus_Size_Knitwear,Plus_Size_Sweatshirts,Women_Plus_Clothing,Women_Plus_Beachwear,Women_Plus_Party_Wear,Women_Plus_Activewear,Women_Plus_Sleep_&_Lounge,Plus_Size_Nightgowns_SleepShirts,Plus_Size_Robes",
    "men":
        "WashaqMen,WashaqUni,Men_Tops,Men_Clothing,Men_Outerwear,Men_Hoodies_&_Sweatshirts,Men_Co_Ords,Men_Bottoms,Men_Denim,Men_Knitwear,Men_Traditional_Cultural_Wear,Men_Active_Tops",
    "shoes":
        "Men_Shoes,Women_Sandals,Women_Flats,Women_Shoes,Men_Sneakers,Men_Sandals_Slides,Women_Boots,Women_Sneakers,Women_Pumps,Women_Fashion_Boots,Men_Loafers,Dress_Shoes,Men_Boots,Women_Slippers,Men_Sandals,Men_Athletic_Shoes,Men_Slippers,Women_Outdoor_Shoes,Women_Wedges_Flatform,Men_Outdoor_Shoes,Men_Clogs,Women_Athletic_Shoes,Men_Flip_Flops_Slides,Men_Work_Safety_Shoes,Women_Clogs,Men_Flip_Flops_&_Slides,Men_Skateboarding_Shoes,Wide_Fit_Pumps,Women_Wedges_&_Flatform,Women_Loafers_Shoes,Men_Canvas_Shoes,boys_shoes",
    "bags":
        "Brands,Men_Bags,Travel_Bags,Wallets_&_Card_Holders,Women_Backpacks,Women_Bag_Sets,Women_Clutches,Women_Crossbody,Women_Shoulder_Bags,Women_Top_Handle_Bags,Women_Tote_Bags",
    "kidsShoes": "boys_shoes",
    "womenShoes":
        "Women_Boots,Women_Flats,Women_Pumps,Women_Sandals,Women_Shoes,Women_Slippers,Women_Sneakers,Women_Wedges_&_Flatforms",
    "menShoes":
        "Men_Loafers,Men_Boots,Men_Shoes,Dress_Shoes,Men_Sneakers,Men_Sandals",
    "kidsBoys":
        "WashaqKids,WashaqKidsBoys,Young_Boys_Bottoms,Young_Boys_Pajamas,Young_Boys_Sets,Young_Boys_Tops",
    "kidsGirls":
        "WashaqKids,WashaqKidsGirls,Young_Girls_Bottoms,Young_Girls_Dresses,Young_Girls_Pajamas,Young_Girls_Sets,Young_Girls_Tops",
    "kids":
        "WashaqKids,WashaqKidsBoys,WashaqKidsGirls,UniSexKidsGirls,Young_Boys_Bottoms,Young_Boys_Pajamas,Young_Boys_Sets,Young_Boys_Tops,Young_Girls_Bottoms,Young_Girls_Dresses,Young_Girls_Pajamas,Young_Girls_Sets,Young_Girls_Tops",
  },
  "basicCategories": [
    {
      "id": "1",
      "name": "ملابس نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "WashaqWomen,WashaqUni,Arabian_Wear,Women_Beachwear,Women_Bottoms,Women_Clothing,Women_Co_Ords,Women_Denim,Women_Dresses,Women_Jumpsuits_Bodysuits,Women_Knitwear,Women_Outerwear,Women_Party_Wear,Women_Suits,Women_Sweatshirts,Women_Tops,Women_Activewear,Women_Sleepwear,Women_Sexy_Lingerie,Women_Bras_&_Panties,Women_Briefs",
    },
    {
      "id": "2",
      "name": "ملابس رجالية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "WashaqMen,WashaqUni,Men_Tops,Men_Clothing,Men_Outerwear,Men_Hoodies_&_Sweatshirts,Men_Co_Ords,Men_Bottoms,Men_Denim,Men_Knitwear,Men_Traditional_Cultural_Wear,Men_Active_Tops",
    },
    {
      "id": "3",
      "name": "ملابس أطفال",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
    },
    {
      "id": "4",
      "name": "مقاسات كبيرة",
      "image": "assets/images/Womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "WashaqPlusWomen,Plus_Size_Dresses,Plus_Size_Bottoms,Plus_Size_Outerwears,Plus_Size_Denim,Plus_Size_Tops,Plus_Size_Co_Ords,Plus_Size_Suits,Plus_Size_Jumpsuits_Bodysuits,Plus_Size_Arabian_Wear,Plus_Size_Knitwear,Plus_Size_Sweatshirts,Women_Plus_Clothing,Women_Plus_Beachwear,Women_Plus_Party_Wear,Women_Plus_Activewear,Women_Plus_Sleep_&_Lounge,Plus_Size_Nightgowns_SleepShirts,Plus_Size_Robes",
    },
    {
      "id": "5",
      "name": "حقائب",
      "image": "assets/images/Bagcat.jpg",
      "main_category": "Bags_&_Luggage",
      "sub_category":
          "Brands,Men_Bags,Travel_Bags,Wallets_&_Card_Holders,Women_Backpacks,Women_Bag_Sets,Women_Clutches,Women_Crossbody,Women_Shoulder_Bags,Women_Top_Handle_Bags,Women_Tote_Bags",
    },
    {
      "id": "6",
      "name": "الأحذية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category":
          "Men_Shoes,Women_Sandals,Women_Flats,Women_Shoes,Men_Sneakers,Men_Sandals_Slides,Women_Boots,Women_Sneakers,Women_Pumps,Women_Fashion_Boots,Men_Loafers,Dress_Shoes,Men_Boots,Women_Slippers,Men_Sandals,Men_Athletic_Shoes,Men_Slippers,Women_Outdoor_Shoes,Women_Wedges_Flatform,Men_Outdoor_Shoes,Men_Clogs,Women_Athletic_Shoes,Men_Flip_Flops_Slides,Men_Work_Safety_Shoes,Women_Clogs,Men_Flip_Flops_&_Slides,Men_Skateboarding_Shoes,Wide_Fit_Pumps,Women_Wedges_&_Flatform,Women_Loafers_Shoes,Men_Canvas_Shoes,boys_shoes",
    },
    {
      "id": "9",
      "name": "ملابس داخلية",
      "image": "assets/images/Undercat.jpg",
      "main_category": "Underwear_&_Sleepwear",
    },
    {
      "id": "15",
      "name": "للمنزل",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
    },
    {
      "id": "17",
      "name": "اكسسوارات",
      "image": "assets/images/ALanding.jpg",
      "main_category": "Apparel_&_Accessories",
    },
    {
      "id": "20",
      "name": "قرطاسية ومكاتب",
      "image": "assets/images/Officecat.jpg",
      "main_category": "Office_&_School_Supplies",
    },
    {
      "id": "21",
      "name": "فيتامينات و العناية بالبشرة",
      "image": "assets/images/Beautycat.jpg",
      "main_category": "Beauty_&_Health",
    },
    {
      "id": "22",
      "name": "الكترونيات",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Electronics",
    },
    {
      "id": "23",
      "name": "ملابس رياضية",
      "image": "assets/images/Sportcat.jpg",
      "main_category": "Sports_&_Outdoor",
    },
  ],
  "secondaryCategories": [
    {
      "id": "7",
      "name": "ملابس أولاد",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category":
          "WashaqKids,WashaqKidsBoys,Young_Boys_Bottoms,Young_Boys_Pajamas,Young_Boys_Sets,Young_Boys_Tops",
    },
    {
      "id": "8",
      "name": "ملابس بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category":
          "WashaqKids,WashaqKidsGirls,Young_Girls_Bottoms,Young_Girls_Dresses,Young_Girls_Pajamas,Young_Girls_Sets,Young_Girls_Tops",
    },
    {
      "id": "12",
      "name": "أحذية ستاتية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category":
          "Women_Boots,Women_Flats,Women_Pumps,Women_Sandals,Women_Shoes,Women_Slippers,Women_Sneakers,Women_Wedges_&_Flatforms",
    },
    {
      "id": "13",
      "name": "أحذية رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category":
          "Men_Loafers,Men_Boots,Men_Shoes,Dress_Shoes,Men_Sneakers,Men_Sandals",
    },
    {
      "id": "14",
      "name": "أحذية أطفال",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "boys_shoes",
    },
  ],
  "kidsShoes": [
    {
      "name": "أحذية أطفال",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "boys_shoes",
    },
  ],
  "men": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "WashaqMen,WashaqUni,Men_Tops,Men_Clothing,Men_Outerwear,Men_Hoodies_&_Sweatshirts,Men_Co_Ords,Men_Bottoms,Men_Denim,Men_Knitwear,Men_Traditional_Cultural_Wear,Men_Active_Tops",
    },
    {
      "name": "بلايز رجالية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Men_Tops,Men_Plus_Size_Tops,Men_Active_Tops",
    },
    {
      "name": "تنسيقات وأطقم رجالية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Men_Co_Ords,Men_Plus_Size_Co_Ords",
    },
    {
      "name": "هوديز رجالية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "Men_Hoodies_&_Sweatshirts,Men_Plus_Size_Hoodies_Sweatshirts",
    },
    {
      "name": "ملابس رجالية سفلية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Men_Bottoms",
    },
    {
      "name": "ملابس رجالية خارجية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Men_Outerwear,Men_Plus_Size_Outerwear",
    },
    {
      "name": "أقمشة جينز رجالية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Men_Denim",
    },
    {
      "name": "الملابس الثقافية التقليدية للرجال",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Men_Traditional_Cultural_Wear",
    },
    {
      "name": "ملابس رياضية رجالية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Men_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "Men_Active_Bottoms,Men_Active_Tops,Men_Activewear, Plus Size Sports Sets",
    },
    {
      "name": "أحذية رجالية",
      "image": "assets/images/Mencat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category":
          "Men_Loafers,Men_Boots,Men_Shoes,Dress_Shoes,Men_Sneakers,Men_Sandals",
    },
  ],
  "women": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "WashaqWomen,WashaqUni,Arabian_Wear,Women_Beachwear,Women_Bottoms,Women_Clothing,Women_Co_Ords,Women_Denim,Women_Dresses,Women_Jumpsuits_Bodysuits,Women_Knitwear,Women_Outerwear,Women_Party_Wear,Women_Suits,Women_Sweatshirts,Women_Tops,Women_Activewear,Women_Sleepwear,Women_Sexy_Lingerie,Women_Bras_&_Panties,Women_Briefs",
    },
    {
      "name": "فساتين",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Dresses",
    },
    {
      "name": "ملابس نسائية سفلية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Bottoms,women_active_bottoms",
    },
    {
      "name": "ملابس نسائية خارجية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Outerwear",
    },
    {
      "name": "أقمشة جينز نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Denim",
    },
    {
      "name": "بلايز نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Tops,Women_Sweatshirts,women_active_tops",
    },
    {
      "name": "ملابس نسائية خليجية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Arabian_Wear",
    },
    {
      "name": "تنسيقات نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Co_Ords",
    },
    {
      "name": "زفاف وسهرات نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Party_Wear",
    },
    {
      "name": "ملابس نسائية سباحة",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Beachwear",
    },
    {
      "name": "بدلات نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Suits",
    },
    {
      "name": "جمبسوت نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Jumpsuits_Bodysuits",
    },
    {
      "name": "ملابس نسائية داخلية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Underwear_&_Sleepwear",
    },
    {
      "name": "اكسسوارات نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Apparel_&_Accessories",
      "sub_category": "Women Accessories",
    },
    {
      "name": "الموضة والجمال نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Beauty_&_Health",
      "sub_category": "",
    },
    {
      "name": "أحذية نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Women Shoes",
    },
  ],
  "womenPlus": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category":
          "WashaqWomen,WashaqUni,Arabian_Wear,Women_Beachwear,Women_Bottoms,Women_Clothing,Women_Co_Ords,Women_Denim,Women_Dresses,Women_Jumpsuits_Bodysuits,Women_Knitwear,Women_Outerwear,Women_Party_Wear,Women_Suits,Women_Sweatshirts,Women_Tops,Women_Activewear,Women_Sleepwear,Women_Sexy_Lingerie,Women_Bras_&_Panties,Women_Briefs",
    },
    {
      "name": "فساتين حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Dresses",
    },
    {
      "name": "ملابس سفلية حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Bottoms",
    },
    {
      "name": "ملابس خارجية حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Outerwears",
    },
    {
      "name": "اقمشة جينز حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Denim",
    },
    {
      "name": "بلايز حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Tops,Plus_Size_Sweatshirts",
    },
    {
      "name": "تنسيقات وأطقم حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Co_Ords",
    },
    {
      "name": "زفاف وسهرات حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Plus_Party_Wear",
    },
    {
      "name": "ملابس سباحة حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Women_Plus_Beachwear",
    },
    {
      "name": "بدلات حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Suits",
    },
    {
      "name": "جمبسوت حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Jumpsuits_Bodysuits",
    },
    {
      "name": "ملابس خليجية حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Women_Apparel,UniSexA,Sports_&_Outdoor",
      "sub_category": "Plus_Size_Arabian_Wear",
    },
    {
      "name": "ملابس رياضية نسائية",
      "image": "assets/images/WLanding.jpg",
      "main_category": "Sports_&_Outdoor",
      "sub_category": "Women_Plus_Size_Activewear",
    },
    {
      "name": "ملابس نوم حجم كبير",
      "image": "assets/images/womenpluscat.jpg",
      "main_category": "Underwear_&_Sleepwear",
      "sub_category": "Women_Plus_Sleep_&_Lounge",
    },
  ],
  "allkids": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
    },
    {
      "name": "بلايز أطفال",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Tops,Young_Boys_Tops",
    },
    {
      "name": "ملابس أطفال سفلية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Bottoms,Young_Boys_Bottoms",
    },
    {
      "name": "بجامات أطفال",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Pajamas,Young_Girls_Pajamas",
    },
  ],
  "girls": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category":
          "WashaqKids,WashaqKidsGirls,Young_Girls_Bottoms,Young_Girls_Dresses,Young_Girls_Pajamas,Young_Girls_Sets,Young_Girls_Tops",
    },
    {
      "name": "فساتين بناتية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Dresses",
    },
    {
      "name": "ملابس علوية بناتية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Tops",
    },
    {
      "name": "ملابس سفلية بناتية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Bottoms",
    },
    {
      "name": " ملابس نوم وبجامات بناتية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Pajamas",
    },
    {
      "name": "أطقم بناتية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Sets, Young_Girls_Outerwear",
    },
  ],
  "boys": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category":
          "WashaqKids,WashaqKidsBoys,Young_Boys_Bottoms,Young_Boys_Pajamas,Young_Boys_Sets,Young_Boys_Tops",
    },
    {
      "name": "بلايز ولادية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Tops",
    },
    {
      "name": "سراويل ولادية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Bottoms",
    },
    {
      "name": "ملابس ولادية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Clothing",
    },
    {
      "name": "أطقم ولادية",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Sets,Young_Boys_Pajamas",
    },
  ],
  "womenAndBaby": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/pregcat.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "baby_clothing,boys_shoes",
    },
    {
      "name": "ملابس أولاد الأطفال",
      "image": "assets/images/pregcat.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "baby_clothing",
    },
    {
      "name": "أحذية الأطفال",
      "image": "assets/images/pregcat.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "boys_shoes",
    },
  ],
  "allShoes": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category":
          "Men_Shoes,Women_Sandals,Women_Flats,Women_Shoes,Men_Sneakers,Men_Sandals_Slides,Women_Boots,Women_Sneakers,Women_Pumps,Women_Fashion_Boots,Men_Loafers,Dress_Shoes,Men_Boots,Women_Slippers,Men_Sandals,Men_Athletic_Shoes,Men_Slippers,Women_Outdoor_Shoes,Women_Wedges_Flatform,Men_Outdoor_Shoes,Men_Clogs,Women_Athletic_Shoes,Men_Flip_Flops_Slides,Men_Work_Safety_Shoes,Women_Clogs,Men_Flip_Flops_&_Slides,Men_Skateboarding_Shoes,Wide_Fit_Pumps,Women_Wedges_&_Flatform,Women_Loafers_Shoes,Men_Canvas_Shoes,boys_shoes",
    },
    {
      "name": "حفايات",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Women_Flats,Men_Loafers",
    },
    {
      "name": "أحذية رياضة",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Sneakers,Women_Sneakers",
    },
    {
      "name": " Boots ",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Boots,Women_Boots",
    },
    {
      "name": " أحذية رسمية رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Loafers,Dress_Shoes",
    },
    {
      "name": " كعوب عالي و أحذية رسمية نسائية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Women_Pumps,Women_Wedges_&_Flatform",
    },
    {
      "name": "صنادل",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Sandals,Women_Sandals",
    },
    {
      "name": " شباشب وأحذية منزل",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Sandals,Women_Slippers ",
    },
    {
      "name": "جزمات",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Shoes,Women_Shoes",
    },
  ],
  "menShoes": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category":
          "Men_Loafers,Men_Boots,Men_Shoes,Dress_Shoes,Men_Sneakers,Men_Sandals",
    },
    {
      "name": "حفايات رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Loafers",
    },
    {
      "name": " Boots رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Boots",
    },
    {
      "name": "جزمات رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Shoes",
    },
    {
      "name": "أحذية رسمية رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Dress_Shoes",
    },
    {
      "name": "أحذية رياضة رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Sneakers",
    },
    {
      "name": " شباشب وصنادل رجالية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes,Baby_&_Kids",
      "sub_category": "Men_Sandals",
    },
  ],
  "womenShoes": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes",
      "sub_category":
          "Women_Boots,Women_Flats,Women_Pumps,Women_Sandals,Women_Shoes,Women_Slippers,Women_Sneakers,Women_Wedges_&_Flatforms",
    },
    {
      "name": " Boots  ستاتية ",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes",
      "sub_category": "Women_Boots",
    },
    {
      "name": "أحذية كعب عالي",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes",
      "sub_category": "Women_Pumps, Women_Wedges_&_Flatform",
    },
    {
      "name": "أحذية مسطحة و حفايات",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes",
      "sub_category": "Women_Flats",
    },
    {
      "name": "أحذية رياضة ستاتية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes",
      "sub_category": "Women_Sneakers",
    },
    {
      "name": "صنادل ستاتية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes",
      "sub_category": "Women_Sandals",
    },
    {
      "name": " شباشب وأحذية منزل ستاتية",
      "image": "assets/images/Shoescat.jpg",
      "main_category": "Shoes",
      "sub_category": "Women_Slippers",
    },
  ],
  "underWare": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Undercat.jpg",
      "main_category": "Underwear_&_Sleepwear",
    },
    {
      "name": " بجامات و روبات",
      "image": "assets/images/Undercat.jpg",
      "main_category": "Underwear_&_Sleepwear",
      "sub_category": "Women_Sleepwear",
    },
    {
      "name": "لانجري",
      "image": "assets/images/Undercat.jpg",
      "main_category": "Underwear_&_Sleepwear",
      "sub_category": "Women_Sexy_Lingerie",
    },
    {
      "name": "ملابس داخلية نسائية",
      "image": "assets/images/Undercat.jpg",
      "main_category": "Underwear_&_Sleepwear",
      "sub_category": "Women_Bras_&_Panties",
    },
    {
      "name": " بجامات و روبات مقاسات كبيرة",
      "image": "assets/images/Undercat.jpg",
      "main_category": "Underwear_&_Sleepwear",
      "sub_category": "Women_plus_Sleep_&_Lounge",
    },
    {
      "name": "سراويل رجالية",
      "image": "assets/images/Undercat.jpg",
      "main_category": "Underwear_&_Sleepwear",
      "sub_category": "men_sleepwear",
    },
  ],
  "home": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
    },
    {
      "name": "أدوات للمطبخ",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
      "sub_category": "Kitchen_&_Dining,Bakeware",
    },
    {
      "name": "ديكور و زينة",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
      "sub_category": "Home_Decor",
    },
    {
      "name": "ملصقات المنزل",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
      "sub_category": "Home_Stickers",
    },
    {
      "name": "أغطية الوسائد والكراسي",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
      "sub_category": "Cushion_Cover",
    },
    {
      "name": "ملوازم الحفلات المهرجانية",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
      "sub_category": "Festival_Party_Supplies",
    },
    {
      "name": "مكاتب وتنظيم",
      "image": "assets/images/Homecat.jpg",
      "main_category": "Home_&_Living",
      "sub_category": "makateb",
    },
  ],
  "apparel": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/ALanding.jpg",
      "main_category": "Apparel_&_Accessories",
    },
    {
      "name": " أوشحة وشالات نسائي",
      "image": "assets/images/ALanding.jpg",
      "main_category": "Apparel_&_Accessories",
      "sub_category": "Women_Scarves_&_Scarf_Accessories",
    },
    {
      "name": " مجوهرات نسائية للمناسبات",
      "image": "assets/images/ALanding.jpg",
      "main_category": "Apparel_&_Accessories",
      "sub_category": "Wedding_Accessories",
    },
    {
      "name": "قبعات وقفازات رجالية",
      "image": "assets/images/ALanding.jpg",
      "main_category": "Apparel_&_Accessories",
      "sub_category": "Men_Accessories",
    },
  ],
  "beauty": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Beauty_&_Health",
    },
    {
      "name": " اكسسوارات الشعر ",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Beauty_&_Health",
      "sub_category": "Hair_Accessories",
    },
    {
      "name": "إكسسوارات الاظافر ",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Beauty_&_Health",
      "sub_category": "Nail_Art_&_Tools",
    },
    {
      "name": "أدوات المكياج",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Beauty_&_Health",
      "sub_category": "Beauty_Tools",
    },
    {
      "name": " تاتو مؤقت",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Beauty_&_Health",
      "sub_category": "Tattoos_&_Body_Art",
    },
  ],
  "electronics": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Electronics",
    },
    {
      "name": " اغلفة وإكسسوارات الهاتف",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Electronics",
      "sub_category": "Cases",
    },
    {
      "name": "وإكسسوارات السيارات",
      "image": "assets/images/ElectCat.jpg",
      "main_category": "Electronics",
      "sub_category": "Car_Seats_&_Accessories",
    },
  ],
  "bags": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Bagcat.jpg",
      "main_category": "Bags_&_Luggage",
    },
    {
      "name": "حقائب يد وكتف نسائية",
      "image": "assets/images/Bagcat.jpg",
      "main_category": "Bags_&_Luggage",
      "sub_category":
          "Women_Crossbody,Women_Shoulder_Bags,Women_Top_Handle_Bags,Brands,Women_Bag_Sets,Travel_Bags",
    },
    {
      "name": "حقائب ظهر نسائية",
      "image": "assets/images/Bagcat.jpg",
      "main_category": "Bags_&_Luggage",
      "sub_category": "Women_Backpacks",
    },
    {
      "name": "كلاتشات نسائية",
      "image": "assets/images/Bagcat.jpg",
      "main_category": "Bags_&_Luggage",
      "sub_category": "Women_Clutches",
    },
    {
      "name": "حقائب توت نسائية",
      "image": "assets/images/Bagcat.jpg",
      "main_category": "Bags_&_Luggage",
      "sub_category": "Women_Tote_Bags",
    },
    {
      "name": "محافظ وحاملات بطاقات",
      "image": "assets/images/Bagcat.jpg",
      "main_category": "Bags_&_Luggage",
      "sub_category": "Wallets_&_Card_Holders,Men_Bags",
    },
  ],
  "sports": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/Sportcat.jpg",
      "main_category": "Sports_&_Outdoor",
    },
    {
      "name": "بلايز وأطقم رياضية للرجال",
      "image": "assets/images/Sportcat.jpg",
      "main_category": "Sports_&_Outdoor",
      "sub_category": "Men_Active_Tops",
    },
    {
      "name": "سراويل رياضية للرجال",
      "image": "assets/images/Sportcat.jpg",
      "main_category": "Sports_&_Outdoor",
      "sub_category": "Men_Active_Bottoms",
    },
    {
      "name": "ملابس رياضية نسائية",
      "image": "assets/images/Sportcat.jpg",
      "main_category": "Sports_&_Outdoor",
      "sub_category": "Women_Active_Tops, women_plus_size_activewear",
    },
    {
      "name": "سراويل رياضية نسائية",
      "image": "assets/images/Sportcat.jpg",
      "main_category": "Sports_&_Outdoor",
      "sub_category": "Women_Active_Bottoms, women_plus_size_activewear",
    },
    {
      "name": "معدات الملاكمة والتمارين",
      "image": "assets/images/Sportcat.jpg",
      "main_category": "Sports_&_Outdoor",
      "sub_category": "Boxing_Equipment",
    },
  ],
  "kids": [
    {
      "name": "جميع الأقسام",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
    },
    {
      "name": "بناطيل أولاد",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Bottoms",
    },
    {
      "name": "ملابس أولاد",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Clothing",
    },
    {
      "name": "أطق وبجاماتم أولاد",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Sets,Young_Boys_Pajamas",
    },
    {
      "name": "بلايز أولاد",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Boys_Tops",
    },
    {
      "name": "بناطيل بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Bottoms",
    },
    {
      "name": "ملابس بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Clothing",
    },
    {
      "name": "فساتين بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Dresses",
    },
    {
      "name": "ملابس خارجية بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Outerwear",
    },
    {
      "name": "بيجامات بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Pajamas",
    },
    {
      "name": "أطقم بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Sets",
    },
    {
      "name": "بلايز بنات",
      "image": "assets/images/KLanding.jpg",
      "main_category": "Baby_&_Kids,UniSexK",
      "sub_category": "Young_Girls_Tops",
    },
  ],
  "perfume": [
    {
      "name": "جميع العطور",
      "image": "assets/images/menparfume.jpg",
      "main_category": "perfume",
      "sub_category": "men_perfume,women_perfume",
    },
    {
      "name": "عطور رجالية",
      "image": "assets/images/menparfume.jpg",
      "main_category": "perfume",
      "sub_category": "men_perfume",
    },
    {
      "name": "عطور نسائية",
      "image": "assets/images/womenoerfume.jpg",
      "main_category": "perfume",
      "sub_category": "women_perfume",
    },
  ],
  "tags": [
    {"tag": "Zeeneh Cosmetics"},
    {"tag": "Christmas"},
    {"tag": "Buy 2 Get 1 Free"},
    {"tag": "flash_sales"},
    {"tag": "Versace"},
    {"tag": "Paco Rabanne"},
    {"tag": "discount"},
    {"tag": "Carolina Herrera"},
    {"tag": "Dolce %26 Gabbana"},
    {"tag": "Calvin Klein"},
    {"tag": "Dior"},
    {"tag": "Armani"},
    {"tag": "Boss"},
    {"tag": "jean paul gaultier"},
    {"tag": "Gucci"},
    {"tag": "Gade"},
    {"tag": "Narciso Rodriguez"},
    {"tag": "Flash Sales"},
    {"tag": "2025 home"},
    {"tag": "Burberry"},
    {"tag": "Paris Blue"},
    {"tag": "Elie Saab"},
    {"tag": "Ajmal"},
    {"tag": "Dunhill London"},
    {"tag": "Chanel"},
    {"tag": "Yves Saint Lauren"},
    {"tag": "mont blanc"},
    {"tag": "Azzaro"},
    {"tag": "Valentino"},
    {"tag": "Lancome"},
    {"tag": "Armaf"},
    {"tag": "Lacoste"},
    {"tag": "Guerlain"},
    {"tag": "Jaguar"},
    {"tag": "Antonio Banderas"},
    {"tag": "Givenchy"},
    {"tag": "Davidoff"},
    {"tag": "Prada"},
    {"tag": "MICHAEL KORS"},
    {"tag": "Franck Olivier"},
    {"tag": "the voice"},
    {"tag": "Estee Lauder"},
    {"tag": "Issey Miyake"},
    {"tag": "Mercedes Benz"},
    {"tag": "Thierry Mugler"},
    {"tag": "Georgie Armani"},
    {"tag": "PEPE JEANS LONDON"},
    {"tag": "Marc Jacobs"},
    {"tag": "TOM FORD"},
    {"tag": "fragrance"},
    {"tag": "Nina Ricci"},
    {"tag": "clinique"},
    {"tag": "mancera"},
    {"tag": "RUE BROCA"},
    {"tag": "Jimmy Choo"},
    {"tag": "Bvlgari"},
    {"tag": "Xerjoff"},
    {"tag": "11.11"},
    {"tag": "Beyonce"},
    {"tag": "Boucheron"},
    {"tag": "AFNAN"},
    {"tag": "lattafa"},
    {"tag": "Rochas"},
    {"tag": "Moschino"},
    {"tag": "HUGO BOSS"},
    {"tag": "Escada"},
    {"tag": "Dsquared2"},
    {"tag": "my perfumes"},
    {"tag": "Agatha"},
    {"tag": "montale"},
    {"tag": "Ralph Lauren"},
    {"tag": "Jacques Bogart"},
    {"tag": "GISADA"},
    {"tag": "Al haramin"},
    {"tag": "Valentino Garavani"},
    {"tag": "Bebe"},
    {"tag": "My Perfumes with a crown on a circle logo"},
    {"tag": "cavalli"},
    {"tag": "THOMAS KOSMALA"},
    {"tag": "horseball"},
    {"tag": "Hollister"},
    {"tag": "Chloe"},
    {"tag": "Joop!"},
    {"tag": "Roberto Cavalli"},
    {"tag": "wadi siji perfumes"},
    {"tag": "GUESS"},
    {"tag": "Revlon"},
    {"tag": "territoire platinum"},
    {"tag": "theoreme homme"},
    {"tag": "billie eilish"},
    {"tag": "Repetto"},
    {"tag": "Ferrari"},
    {"tag": "Tiffany"},
    {"tag": "Jacomo"},
    {"tag": "trussardi"},
    {"tag": "Marina de bourbon"},
    {"tag": "nautica"},
    {"tag": "ELIZABETH ARDEN"},
    {"tag": "MYSTERIOUS TOUCH"},
    {"tag": "reyane tradition"},
    {"tag": "Dumont"},
    {"tag": "JIVAGO"},
  ],
  "tagsMen": [
    {"tag": "Zeeneh Cosmetics"},
    {"tag": "Versace"},
    {"tag": "Paco Rabanne"},
    {"tag": "Carolina Herrera"},
    {"tag": "Dolce %26 Gabbana"},
    {"tag": "Calvin Klein"},
    {"tag": "Dior"},
    {"tag": "Armani"},
    {"tag": "Boss"},
    {"tag": "jean paul gaultier"},
    {"tag": "Gucci"},
    {"tag": "Gade"},
    {"tag": "Narciso Rodriguez"},
    {"tag": "Burberry"},
    {"tag": "Paris Blue"},
    {"tag": "Ajmal"},
    {"tag": "Dunhill London"},
    {"tag": "Chanel"},
    {"tag": "Yves Saint Lauren"},
    {"tag": "mont blanc"},
    {"tag": "Azzaro"},
    {"tag": "Valentino"},
    {"tag": "Armaf"},
    {"tag": "Lacoste"},
    {"tag": "Guerlain"},
    {"tag": "Jaguar"},
    {"tag": "Givenchy"},
    {"tag": "Davidoff"},
    {"tag": "Prada"},
    {"tag": "Franck Olivier"},
    {"tag": "the voice"},
    {"tag": "Issey Miyake"},
    {"tag": "Mercedes Benz"},
    {"tag": "Thierry Mugler"},
    {"tag": "Georgie Armani"},
    {"tag": "PEPE JEANS LONDON"},
    {"tag": "TOM FORD"},
    {"tag": "fragrance"},
    {"tag": "clinique"},
    {"tag": "mancera"},
    {"tag": "RUE BROCA"},
    {"tag": "Jimmy Choo"},
    {"tag": "Bvlgari"},
    {"tag": "Xerjoff"},
    {"tag": "AFNAN"},
    {"tag": "lattafa"},
    {"tag": "Rochas"},
    {"tag": "HUGO BOSS"},
    {"tag": "Dsquared2"},
    {"tag": "my perfumes"},
    {"tag": "montale"},
    {"tag": "Ralph Lauren"},
    {"tag": "GISADA"},
    {"tag": "Al haramin"},
    {"tag": "Valentino Garavani"},
    {"tag": "My Perfumes with a crown on a circle logo"},
    {"tag": "THOMAS KOSMALA"},
    {"tag": "Hollister"},
    {"tag": "Joop!"},
    {"tag": "Roberto Cavalli"},
    {"tag": "wadi siji perfumes"},
    {"tag": "GUESS"},
    {"tag": "territoire platinum"},
    {"tag": "theoreme homme"},
    {"tag": "Jacomo"},
    {"tag": "nautica"},
    {"tag": "Dumont"},
    {"tag": "JIVAGO"},
  ],
  "womenTags": [
    {"tag": "Zeeneh Cosmetics"},
    {"tag": "Versace"},
    {"tag": "Paco Rabanne"},
    {"tag": "Carolina Herrera"},
    {"tag": "Dolce %26 Gabbana"},
    {"tag": "Calvin Klein"},
    {"tag": "Dior"},
    {"tag": "Armani"},
    {"tag": "Boss"},
    {"tag": "jean paul gaultier"},
    {"tag": "Gucci"},
    {"tag": "Gade"},
    {"tag": "Narciso Rodriguez"},
    {"tag": "Burberry"},
    {"tag": "Paris Blue"},
    {"tag": "Elie Saab"},
    {"tag": "Ajmal"},
    {"tag": "Chanel"},
    {"tag": "Yves Saint Lauren"},
    {"tag": "mont blanc"},
    {"tag": "Valentino"},
    {"tag": "Lancome"},
    {"tag": "Armaf"},
    {"tag": "Lacoste"},
    {"tag": "Guerlain"},
    {"tag": "Antonio Banderas"},
    {"tag": "Givenchy"},
    {"tag": "Prada"},
    {"tag": "MICHAEL KORS"},
    {"tag": "Franck Olivier"},
    {"tag": "the voice"},
    {"tag": "Estee Lauder"},
    {"tag": "Issey Miyake"},
    {"tag": "Thierry Mugler"},
    {"tag": "Georgie Armani"},
    {"tag": "PEPE JEANS LONDON"},
    {"tag": "Marc Jacobs"},
    {"tag": "TOM FORD"},
    {"tag": "fragrance"},
    {"tag": "Nina Ricci"},
    {"tag": "clinique"},
    {"tag": "mancera"},
    {"tag": "RUE BROCA"},
    {"tag": "Jimmy Choo"},
    {"tag": "Bvlgari"},
    {"tag": "Xerjoff"},
    {"tag": "Beyonce"},
    {"tag": "Boucheron"},
    {"tag": "AFNAN"},
    {"tag": "lattafa"},
    {"tag": "Moschino"},
    {"tag": "HUGO BOSS"},
    {"tag": "Escada"},
    {"tag": "Dsquared2"},
    {"tag": "my perfumes"},
    {"tag": "Agatha"},
    {"tag": "montale"},
    {"tag": "GISADA"},
    {"tag": "Valentino Garavani"},
    {"tag": "My Perfumes with a crown on a circle logo"},
    {"tag": "horseball"},
    {"tag": "Hollister"},
    {"tag": "Chloe"},
    {"tag": "Roberto Cavalli"},
    {"tag": "wadi siji perfumes"},
    {"tag": "GUESS"},
    {"tag": "billie eilish"},
    {"tag": "Repetto"},
    {"tag": "trussardi"},
    {"tag": "ELIZABETH ARDEN"},
    {"tag": "MYSTERIOUS TOUCH"},
    {"tag": "JIVAGO"},
  ],
};
