// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TbNW9TpYgblN4Q10SrMPm9fLPxL_GjU',
    appId: '1:47403596173:web:78684edf729d02bc6a25c4',
    messagingSenderId: '47403596173',
    projectId: 'fawri-df598',
    authDomain: 'fawri-df598.firebaseapp.com',
    databaseURL: 'https://fawri-df598-default-rtdb.firebaseio.com',
    storageBucket: 'fawri-df598.firebasestorage.app',
    measurementId: 'G-PYW27KEBV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ierkb6f3OJ94clfcUZv32vPKsty8HfQ',
    appId: '1:47403596173:android:78a191904799560e6a25c4',
    messagingSenderId: '47403596173',
    projectId: 'fawri-df598',
    databaseURL: 'https://fawri-df598-default-rtdb.firebaseio.com',
    storageBucket: 'fawri-df598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf8UfFi7BTzAYfXIfrhV8-dFgvO2Z2L7c',
    appId: '1:47403596173:ios:53f32eab502700276a25c4',
    messagingSenderId: '47403596173',
    projectId: 'fawri-df598',
    databaseURL: 'https://fawri-df598-default-rtdb.firebaseio.com',
    storageBucket: 'fawri-df598.firebasestorage.app',
    androidClientId:
        '47403596173-1pes8vvvr2pepb8amblkmgd03911djb3.apps.googleusercontent.com',
    iosClientId:
        '47403596173-ke12nt4tuvta17nvp3t9ghogpj4l0lh0.apps.googleusercontent.com',
    iosBundleId: 'co.fawri.fawri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACyMCBLC44D9cG_vCRM2MDTrgT6hnbtPA',
    appId: '1:47403596173:ios:4e8e9839c765838b6a25c4',
    messagingSenderId: '47403596173',
    projectId: 'fawri-df598',
    databaseURL: 'https://fawri-df598-default-rtdb.firebaseio.com',
    storageBucket: 'fawri-df598.firebasestorage.app',
    androidClientId:
        '47403596173-4ag7rbd5bv1u8s91ccsdniu16v7nopvk.apps.googleusercontent.com',
    iosClientId:
        '47403596173-if1mi3udsnghdbeap4om4ffradiviseb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fawriAppRefactor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_zyXpnTUJKCiwFy2lIkPrub4S8WmhWs',
    appId: '1:47403596173:web:70d3f79fd56ae4026a25c4',
    messagingSenderId: '47403596173',
    projectId: 'fawri-df598',
    authDomain: 'fawri-df598.firebaseapp.com',
    databaseURL: 'https://fawri-df598-default-rtdb.firebaseio.com',
    storageBucket: 'fawri-df598.firebasestorage.app',
    measurementId: 'G-GXF0YGCZ0L',
  );
}
